spring:  
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml
  datasource: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/asi?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1 from dual
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
#      filters: stat,wall
      filters: stat
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      stat-view-servlet:
        allow: 127.0.0.1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    servlet:
      load-on-startup: 1 
      
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true
    enabled: true
    baseline-version: 1.0.0
    sql-migration-prefix: v
    sql-migration-suffixes: .sql

  
#mybatis:
#  type-aliases-package: com.boot.kaizen.model,com.boot.kaizen.model.lteFddModel,com.boot.kaizen.model.lte,com.boot.kaizen.dao.log
#  mapper-locations: classpath:/mybatis-mappers/**/*.xml
#  configuration:
#    mapUnderscoreToCamelCase: true




mybatis-plus:
  type-aliases-package: com.boot.kaizen.model,com.boot.kaizen.model.log
  mapper-locations: classpath:/mybatis-mappers/**/*.xml
  global-config:
    #驼峰
    db-column-underline: true
    field-strategy: 2
    id-type: 3
    #逻辑删除
    logic-delete-value: 0
    logic-not-delete-value: 1
    refresh-mapper: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    
pagehelper:
    helperDialect: mysql
    reasonable: false
    supportMethodsArguments: true
    params: true
    
files:
  path: ${file-path:d:/kaizen/doc}     #所有文件存储的根路径
  nobitDocExcel: d:/kaizen/doc/excelModel/shanghaiAppEcportModel.xls
    
logging:
  config: classpath:logback-admin.xml
  
  
log: 
  level:
    root: info
    my: debug
  file: d:/kaizen/doc/logs/admin-server.log
  dayfile: d:/kaizen/doc/logs/day.log
  maxsize: 30MB
  
  
  
token: 
  expire:
    seconds: 7200
  jwtSecret: (XIAO:)_$^11244^%$_(WEI:)_@@++--(LAO:)_++++_.sds_(SHI:)
  
server:
  port: 8081
  
 
redis: 
  db: 0
  max-idle: 10     # 连接池中的最大空闲连接 
  min-idle: 10     # 连接池中的最小空闲连接 
  max-total: 10    
  max-wait-millis: 10000    #毫秒
  test-on-borrow: true       
  timeout: 5000             #超时
  sentinel-master: mymaster
  sentinel-nodes: 192.168.233.21:26379|192.168.233.23:26379|192.168.233.25:26379   ##哨兵集群
